plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.gms.google-services'
}

android {
    compileSdkVersion 35
    namespace "infosecadventures.allsafe"

    defaultConfig {
        applicationId "infosecadventures.allsafe"
        minSdkVersion 21
        targetSdk 35
        versionCode 6
        versionName "1.6"
    }

    lint {
        baseline = file("lint-baseline.xml")
        abortOnError = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        releaseLight {
            initWith release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-light.pro'
        }
        releaseHeavy {
            initWith release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-heavy.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_18
        targetCompatibility JavaVersion.VERSION_18
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
    kotlin {
        jvmToolchain(18)
    }
    kotlinOptions {
        jvmTarget = "18"
    }

    packagingOptions {
        pickFirst 'AndroidManifest.xml'
    }

    ndkVersion = '25.1.8937393'

//    applicationVariants.all { variant ->
//        variant.javaCompileProvider.get().doLast {
//            runAllatori(variant)
//        }
//    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.10.0')
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.0'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.8.9'
    implementation 'androidx.navigation:navigation-ui-ktx:2.8.9'
    implementation 'com.google.firebase:firebase-database-ktx:21.0.0'
    implementation 'com.google.firebase:firebase-storage-ktx:21.0.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation "com.squareup.okhttp3:okhttp:4.9.0"
    implementation 'com.scottyab:rootbeer-lib:0.0.8'
}

//def runAllatori(variant) {
//    println "Path to allatori.jar should be $rootDir/allatori/allatori.jar"
//    println "Path to allatori.xml configuration file should be $projectDir/allatori.xml"
//
//    String classesRoot = variant.javaCompileProvider.get().destinationDirectory.get()
//    String kotlinRoot = "${buildDir}/tmp/kotlin-classes/${variant.name}"
//
//    copy {
//        from "$projectDir/allatori.xml"
//        into "$classesRoot/../"
//        expand(classesRoot: classesRoot,
//                kotlinRoot: kotlinRoot,
//                androidJar: "${android.sdkDirectory}/platforms/${android.compileSdkVersion}/android.jar",
//                classpathJars: variant.javaCompileProvider.get().classpath.asPath,
//                logFile: 'allatori-log.xml')
//        rename('allatori.xml', 'allatori-expanded.xml')
//    }
//
//    new File("$classesRoot-obfuscated").deleteDir()
//    // Kotlin support
//    new File("$kotlinRoot-obfuscated").deleteDir()
//
//    javaexec {
//        mainClass = 'com.allatori.Obfuscate'
//        classpath = files("$rootDir/allatori/allatori.jar")
//        args "$classesRoot/../allatori-expanded.xml"
//    }
//
//    new File(classesRoot).deleteDir()
//    new File("$classesRoot-obfuscated").renameTo(new File(classesRoot))
//    // Kotlin support
//    if (new File("$kotlinRoot-obfuscated").exists()) {
//        new File(kotlinRoot).deleteDir()
//        new File("$kotlinRoot-obfuscated").renameTo(new File(kotlinRoot))
//    }
//}